project:
  type: website
  output-dir: docs

website:
  image: "assets/images/seo.webp"
  favicon: "assets/favicon.png"
  navbar:
    logo: "assets/logos/nbis-scilifelab.webp"
    logo-alt: "logo"
    right:
      - text: "Home"
        href: "index.html"
        aria-label: "Home"
      - text: "Schedule"
        href: "home_schedule.html"
        aria-label: "Schedule"
      - text: "Contents"
        href: "home_contents.html"
        aria-label: "Contents"
      - text: "Syllabus"
        href: "home_syllabus.html"
        aria-label: "Syllabus"
      - text: "Precourse"
        href: "home_precourse.html"
        aria-label: "Pre-course"
      - text: About
        href: "home_about.html"
        aria-label: "About"
  page-footer:
    border: false
    left: "{{< meta current_year >}} [NBIS](https://nbis.se) | [GPL-3 License](https://choosealicense.com/licenses/gpl-3.0/)"
    right: "Published with [Quarto](https://quarto.org/) v{{< meta quarto_version >}}"
  site-url: "https://royfrancis.github.io/specky/"
  open-graph: true

format:
  html:
    quarto-required: ">=1.4.0"
    include-in-header: "assets/include_head.html"
    include-before-body: "assets/include_body_before.html"
    include_after_body: "assets/include_body_after.html"
    theme: "assets/css/styles.scss"
    smooth-scroll: true
    toc: true
    toc-depth: 4
    toc-location: right
    number-sections: true
    number-depth: 4
    code-fold: false
    code-tools: false
    code-copy: true
    code-overflow: wrap
    df-print: paged
    standalone: false
    fig-align: left
    title-block-banner: "assets/images/banner.webp"
    subtitle: "Specky quarto theme"
    callout-icon: true
    date:  last-modified
    date-format: "DD-MMM-YYYY"
    image: "assets/images/featured.webp"
    lightbox: auto
  revealjs:
    quarto-required: ">=1.4.0"
    include-in-header: "assets/include_head.html"
    include-before-body: "assets/include_body_before.html"
    include_after_body: "assets/include_body_after.html"
    theme: ["default","assets/css/slides.scss"]
    df-print: paged
    width: 1280
    height: 720
    transition: "fade"
    transition-speed: "fast"
    smaller: false
    incremental: false
    scrollable: false
    slide-level: 2
    slide-number: true
    progress: true
    date:  last-modified
    date-format: "DD-MMM-YYYY"
    fig-align: left
    chalkboard: true
    callout-icon: true
    image: "/assets/images/featured.webp"
    hero: "/assets/images/slide-hero.webp"
    title-slide-attributes:
      data-background-image: "/assets/images/cover.webp"
      data-background-size: "cover"
      data-background-opacity: "1"
    subtitle: "Specky quarto theme"
    header-logo-left: /assets/logos/nbis.webp
    header-logo-left-height: 25px
    header-logo-left-url: https://royfrancis.github.io/specky/home_contents.html
    header-logo-right: /assets/logos/scilifelab.webp
    header-logo-right-height: 25px
    header-logo-right-url: https://royfrancis.github.io/specky/home_contents.html
    template-partials:
      - "/assets/title-slide.html"

execute:
  eval: true
  echo: true
  warning: false
  message: false
  freeze: auto

filters:
  - assets/custom.lua
  - assets/fold-results.lua
  - reveal-logo
  - fontawesome

